FROM ubuntu

ARG COMMON_MACHINE_SSH_PASSWORD

# --- SSH:start ---
# Install SSH server
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd

# Configure SSH
RUN echo "root:$COMMON_MACHINE_SSH_PASSWORD" | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
# --- SSH:end ---

# Expose SSH port
EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]

